apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    description: WAN LAN speedtest
  labels:
    k8s-app: speedtest
  name: speedtest
spec:
  selector:
    matchLabels:
      k8s-app: speedtest
  template:
    metadata:
      annotations:
        description: WAN LAN speedtest
      labels:
        k8s-app: speedtest
      name: speedtest
    spec:
      containers:
      - env:
        - name: tz
          value: UTC
        image: marvinmarvin/docker-k8s-speedtest
        imagePullPolicy: Always
        name: speedtest
#        volumeMounts:
#        - mountPath: /etc/cron.d
#          name: k8s-cfg-speedtest
#          readOnly: true
        volumeMounts:
        - mountPath: /etc/cron.d
          name: k8s-speedtest
          subPath: speedtest
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
#      - name: k8s-cfg-speedtest
#        hostPath:
#          path: /root/k8s-cfg/speedtest
#          type: Directory
      - name: k8s-speedtest
        persistentVolumeClaim:
          claimName: k8s-pvc
      dnsPolicy: ClusterFirst
      hostNetwork: false
#      nodeSelector:
#        location: lan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
