apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: WAN LAN speedtest
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: speedtest
  name: speedtest
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/speedtest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: speedtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: WAN LAN speedtest
      creationTimestamp: null
      labels:
        k8s-app: speedtest
      name: speedtest
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        image: marvinmarvin/docker-k8s-speedtest
        imagePullPolicy: Always
        name: speedtest
        volumeMounts:
        - mountPath: /etc/cron.d
          name: k8s-cfg-speedtest
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-speedtest
        hostPath:
          path: /root/k8s-cfg/speedtest
          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: vps-us-ny-kube-1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
